---
driver:
  name: exec

provisioner:
  name: chef_zero
  install_strategy: skip

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
  - name: windows-2019
  - name: macos-10.15

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      chef_client:
        chef_license: accept
