---
driver:
  name: localhost

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.12.9

verifier:
  name: inspec

platforms:
  - name: windows-2019

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
