---
driver:
  name: localhost

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows-2019

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
