name: CI

on: [push]

env:
  CHEF_LICENSE: accept

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Chef
      run: |
           . { iwr -useb https://omnitruck.chef.io/install.ps1 } | iex; install -channel stable -project chefdk
           c:\opscode\chefdk\bin\chef.bat shell-init powershell | iex;
    - name: Check Kitchen Version
      run: c:\opscode\chefdk\bin\chef.bat exec kitchen --version
    - name: Diagnose
      run: c:\opscode\chefdk\bin\chef.bat exec kitchen diagnose --all default-windows-2019
    - name: Verify
      run: c:\opscode\chefdk\bin\chef.bat exec kitchen converge --debug default-windows-2019

  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Chef
      run: curl -L https://www.chef.io/chef/install.sh | sudo bash -s -- -P chefdk
    - name: Verify
      run: chef exec kitchen verify default-ubuntu-1804

  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Chef
      run: curl -L https://www.chef.io/chef/install.sh | sudo bash -s -- -P chefdk
    - name: Verify
      run: chef exec kitchen verify default-macos-1015
